query products(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $vendor: String
  $category: String
) {
  products(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    vendor: $vendor
    category: $category
  ) {
    data {
      id
      slug
      name
      type
      price
      stock
      img
      time
      vendor {
        id
        firstName
        lastName
        phone
        email
        info {
          restaurant
          kitchenPhotos
        }
      }
    }
    count
    pageSize
    page
  }
}
