query coupons($page: Int,$search: String, $limit:Int, $sort:String) {
  coupons(page: $page, search: $search, limit:$limit, sort:$sort) {
    count
    page
    pageSize
    data {
      id
      code
      value
      type
      info
      msg
      text
      terms
      color
      minimumCartValue
      maxAmount
      from
      to
      active
      createdAt
      updatedAt
    }
  }
}
