query slots($page: Int, $search: String, $limit: Int, $sort: String) {
  slots(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      val
      slug
      info
      active
    }
  }
}
