mutation addToCart($qty: Int!, $pid: ID!, $replace: Boolean) {
  addToCart(qty: $qty, pid: $pid, replace: $replace) {
    items {
      pid
      name
      slug
      qty
      price
      img
    }
    qty
    subtotal
    discount {
      code
      value
      text
      amount
    }
    shipping {
      charge
    }
    total
    tax {
      cgst
      sgst
      igst
    }
  }
}
