mutation applyCoupon($code: String!) {
  applyCoupon(code: $code) {
    items {
      pid
      name
      slug
      qty
      rate
      img
    }
    qty
    subtotal
    discount {
      code
      value
      text
    }
    shipping {
      charge
    }
    total
    tax {
      cgst
      sgst
      igst
    }
  }
}
