query banners($page: Int,$search: String, $limit:Int, $sort:String, $type: String, $active: Boolean) {
  banners(page: $page, search: $search, limit:$limit, sort:$sort, type:$type, active: $active) {
    count
    page
    pageSize
    data {
      id
      link
      heading
      img
      type
      active
      createdAt
      updatedAt
    }
  }
}
