mutation capturePay($id: String!, $oid: String!) {
  capturePay(payment_id: $id, oid: $oid) {
    id
    user {
      firstName
      lastName
    }
    orderNo
    amount {
      total
      subtotal
      shipping
      qty
      tax
    }
    address {
      firstName
      lastName
      address
    }
    items {
      pid
      name
      slug
      qty
      img
      price
      status
      vendor {
        restaurant
      }
    }
    comment
    cancellationReason
    cancellationComment
    returnComment
    payment {
      id
    }
    reviewed
  }
}
