query orders {
  orders {
    count
    page
    pageSize
    data {
      id
      orderNo
      createdAt
      amount {
        qty
        subtotal
        tax{
          cgst
          sgst
          igst
        }
        discount
        total
        shipping
      }
      address {
        firstName
        lastName
        address
        coords {
          lat
          lng
        }
      }
      items {
        pid
        name
        img
        slug
        price
        qty
        status
        vendor {
          restaurant
        }
      }
    }
  }
}
