query order($id: ID!) {
  order(id: $id) {
    orderNo
    payment{
      method
      amount
      status
    }
    amount {
      qty
      subtotal
      tax{
        cgst
        sgst
        igst
      }
      discount
      total
      shipping
    }
    address {
      firstName
      lastName
      address
      coords {
        lat
        lng
      }
    }
    items {
      pid
      name
      img
      slug
      price
      qty
      vendor {
        restaurant
      }
      status
    }
  }
}
